################################################
# 	
#           Author: Wallace Vidal Noronha
#           Github: https://github.com/wallace-noronha/
#													                         
#    For elastticsearch starts, run the following command:                                                                                                      
# 	- sudo sysctl -w vm.max_map_count=262144							                                                                                        
################################################

version: '3.3'

services:

    zookeeper1:
        image: confluentinc/cp-zookeeper
        hostname: zookeeper1
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
        environment:
            - ZOOKEEPER_SERVER_ID=1
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_TICK_TIME=2000
            - ZOOKEEPER_INIT_LIMIT=5
            - ZOOKEEPER_SYNC_LIMIT=2
            - ZOOKEEPER_SERVERS=zookeeper1:2888:3888;zookeeper2:2889:3889;zookeeper3:2890:3890
            
    zookeeper2:
        image: confluentinc/cp-zookeeper
        hostname: zookeeper2
        ports:
            - "2182:2181"
            - "2889:2888"
            - "3889:3888"
        environment:
            - ZOOKEEPER_SERVER_ID=2
            - ZOOKEEPER_CLIENT_PORT=2182
            - ZOOKEEPER_TICK_TIME=2000
            - ZOOKEEPER_INIT_LIMIT=5
            - ZOOKEEPER_SYNC_LIMIT=2
            - ZOOKEEPER_SERVERS=zookeeper1:2888:3888;zookeeper2:2889:3889;zookeeper3:2890:3890
            
    zookeeper3:
        image: confluentinc/cp-zookeeper
        hostname: zookeeper3
        ports:
            - "2183:2181"
            - "2890:2888"
            - "3890:3888"
        environment:
            - ZOOKEEPER_SERVER_ID=3
            - ZOOKEEPER_CLIENT_PORT=2183
            - ZOOKEEPER_TICK_TIME=2000
            - ZOOKEEPER_INIT_LIMIT=5
            - ZOOKEEPER_SYNC_LIMIT=2
            - ZOOKEEPER_SERVERS=zookeeper1:2888:3888;zookeeper2:2889:3889;zookeeper3:2890:3890
    
    kafka1:
        image: confluentinc/cp-kafka
        hostname: kafka1
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
        ports:
            - "9091:9091"
        environment:
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9091
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
            - KAFKA_BROKER_ID=1
            - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093
            - ZOOKEEPER=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
    
    kafka2:
        image: confluentinc/cp-kafka
        hostname: kafka2
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
        ports:
            - "9092:9092"
        environment:
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
            - KAFKA_BROKER_ID=2
            - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093
            - ZOOKEEPER=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
    
    kafka3:
        image: confluentinc/cp-kafka
        hostname: kafka3
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
        ports:
            - "9093:9093"
        environment:
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9093
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
            - KAFKA_BROKER_ID=3
            - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093
            - ZOOKEEPER=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
            
    schemaregistry:
        image: confluentinc/cp-schema-registry
        hostname: schemaregistry
        restart: on-failure
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
        ports:
            - "8081:8081"
        environment:
            - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
            - SCHEMA_REGISTRY_HOST_NAME=localhost
            - SCHEMA_REGISTRY_LISTNERS=http://localhost:8081

    nifi:
        image: apache/nifi
        hostname: nifi
        ports:
            - "8888:8888"
            - "8080:8080"
        expose:
            - "8888"
        environment:
            - NIFI_WEB_HTTP_PORT=8080
            - NIFI_CLUSTER_IS_NODE=true
            - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
            - NIFI_ZK_CONNECT_STRING=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
            - NIFI_ELECTION_MAX_WAIT=1 min
      
    elasticsearch:
        image: elasticsearch:7.4.1
        hostname: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - cluster.initial_master_nodes=elasticsearch
            - bootstrap.memory_lock=true
            - xpack.security.enabled=true
            - xpack.security.transport.ssl.enabled=false
            - ELASTIC_PASSWORD=elastic
        ulimits:
            nproc: 65535
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9300:9300"
            
    kibana:
        image: kibana:7.4.1
        hostname: kibana
        environment:
            - ELASTICSEARCH_URL="http://elasticsearch:9200"
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=elastic
            - xpack.security.enabled=true
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch