################################################
# 	
#           Author: Wallace Vidal Noronha
#           Github: https://github.com/wallace-noronha/
#													                         
#    For elastticsearch starts, run the following command:                                                                                                      
# 	- sudo sysctl -w vm.max_map_count=262144							                                                                                        
################################################

version: '3.3'

services:

    zookeeper:
        image: confluentinc/cp-zookeeper
        container_name: zookeeper
        hostname: zookeeper
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
        environment:
            - ZOOKEEPER_SERVER_ID=1
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_TICK_TIME=2000
            - ZOOKEEPER_INIT_LIMIT=5
            - ZOOKEEPER_SYNC_LIMIT=2
            - ZOOKEEPER_SERVERS=zookeeper:2888:3888
            
    kafka:
        image: confluentinc/cp-kafka
        container_name: kafka
        hostname: kafka
        depends_on:
            - zookeeper
        ports:
            - "9091:9091"
        environment:
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9091
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_BROKER_ID=1
            - BOOTSTRAP_SERVERS=kafka:9091
            - ZOOKEEPER=zookeeper:2181
    
    schemaregistry:
        image: confluentinc/cp-schema-registry
        container_name: schemaregistry
        hostname: schemaregistry
        restart: on-failure
        depends_on:
            - zookeeper
        ports:
            - "8081:8081"
        environment:
            - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
            - SCHEMA_REGISTRY_HOST_NAME=localhost
            - SCHEMA_REGISTRY_LISTNERS=http://localhost:8081

    nifi:
        image: apache/nifi
        container_name: nifi
        hostname: nifi
        ports:
            - "8888:8888"
            - "8080:8080"
        expose:
            - "8888"
        environment:
            - NIFI_WEB_HTTP_PORT=8080
            - NIFI_CLUSTER_IS_NODE=true
            - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
            - NIFI_ZK_CONNECT_STRING=zookeeper:2181
            - NIFI_ELECTION_MAX_WAIT=1 min
      
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        hostname: elasticsearch
        environment:
            - ELASTIC_PASSWORD=elastic
            - bootstrap.memory_lock=true
        volumes: 
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./elastic-certs/:/usr/share/elasticsearch/config/certs/
        ports:
            - "9200:9200"

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.4.1
        hostname: kibana
        environment:
            - ELASTICSEARCH_URL="https://elasticsearch:9200"
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=elastic
            - xpack.security.enabled=true
        volumes: 
            - ./kibana.yml:/usr/share/kibana/config/kibana.yml
            - ./elastic-certs/:/usr/share/kibana/config/certs/
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch